In [2]:
import numpy as np
from sentence_transformers import SentenceTransformer

C:\Users\dinne\OneDrive\Desktop\Projects\Database Search\venv\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [3]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\dinne\OneDrive\Desktop\Projects\Database Search\venv\Lib\site-packages\huggingface_hub\file_download.py:159: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\dinne\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

C:\Users\dinne\OneDrive\Desktop\Projects\Database Search\venv\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [5]:
split_docs = sorted(["The dog jumped over the cat"][0].split(' '))
split_docs

['The', 'cat', 'dog', 'jumped', 'over', 'the']

In [6]:
docs = ["The dog jumped over the cat"]
docs

['The dog jumped over the cat']

In [7]:
embeddings = model.encode(docs)

C:\Users\dinne\OneDrive\Desktop\Projects\Database Search\venv\Lib\site-packages\transformers\models\bert\modeling_bert.py:439: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(


In [8]:
docs2 = ["The cat jumped over the dog"]

In [9]:
split_docs2 = sorted(docs2[0].split(' '))
split_docs2

['The', 'cat', 'dog', 'jumped', 'over', 'the']

In [10]:
embeddings2 = model.encode(docs2)

In [11]:
model.similarity(embeddings,embeddings)

tensor([[1.]])

In [12]:
model.similarity(embeddings,embeddings2)

tensor([[0.9895]])

In [13]:
embeddings3 = model.encode(["The dog is hot from jumping"])

In [14]:
model.similarity(embeddings,embeddings3)

tensor([[0.4310]])

In [15]:
embeddings4 = model.encode(["The weather is hot"])
model.similarity(embeddings,embeddings4)

tensor([[-0.0660]])

In [16]:
embeddings2

array([[ 4.72092405e-02,  3.36050168e-02,  6.90095797e-02,
         6.85966536e-02, -1.26861362e-02, -6.25285786e-03,
        -3.72543558e-02,  1.55753251e-02,  2.41127927e-02,
         2.21971259e-03,  7.17992485e-02,  2.92151496e-02,
         5.03158243e-03, -6.37696683e-02,  4.89645451e-03,
         1.07080513e-03, -1.23178750e-01,  9.51719750e-03,
         5.84049113e-02, -1.34706302e-02, -2.93736942e-02,
        -4.55944724e-02, -1.06726689e-02, -4.11552712e-02,
        -3.63231413e-02,  3.73865589e-02, -8.08678567e-02,
        -6.92620650e-02,  1.39805051e-02, -1.62780937e-02,
        -2.12400239e-02, -8.98966752e-03, -3.35779563e-02,
         5.97752519e-02, -6.10135794e-02, -7.63887540e-02,
         6.19943030e-02,  3.30314389e-03,  3.82678211e-02,
         1.23094991e-01, -3.98203135e-02,  7.74866808e-03,
        -1.22558326e-02, -2.10482674e-03, -3.81270200e-02,
         6.25126585e-02, -1.30795864e-02, -6.36047497e-02,
         3.17580141e-02,  5.67504279e-02, -1.24570988e-0